### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by stevenli5** [CommWebTeam/en_to_fr_mapper#32]
**readme:**
- Table of Contents should become a header and all the list elements can be decreased by one level (it looks messy with all the levels)
- The example in "2. Extra tag in the French document" doesn't have the {ITALIC-OPEN} placeholder, don't know if you'd like to add this to the example
- Is it still the case where we close off tags with »? Would > be easier? Since we'd need to have » copied in our clipboard all throughout.
- "3. Different positioning of text around tags" --> After reading this it's a bit unclear. Unsure of why carnivore in french should be before the </span>, since positioning can be different in French (e.g. the blue flower / la fleur bleue). Maybe I'm misunderstanding this example.
- "If the line or tag contains the substring “aragraph” (for “paragraph” / “Paragraph”), ignores differences in numbers, so that differing paragraph numbers won’t prevent a match." --> just want to make sure that no French is being used here-- since there's an "e" at the end of paragraphe for French

**HTML page:**
- Specify if the Dreamweaver-generated HTML pages should have been passed through the Dreamweaver formatter tool (although I don't think it's necessary so this probably isn't needed)

**Comment by hughdingb58** [comment]
Implemented most of these or clarified accordingly, e.g. for the second suggestion I added a mention in the readme that the example lists don't include markers. For the HTML page, using the dw paste formatting tool is indeed unnecessary so I'll leave it out.
